import threading as _threading
import tkinter as _tk
from .bot import BotController as _BotController

class IHSRunner(_tk.Tk):
    """Instantiate and run a runner window.

    Args:
        bot: (BotController): An instance of the `BotController` object.
        light_port (int): Port number of the light sensor.
        reset_file_path (str): File path of the 'reset' program. Leave as empty string if not applicable.
    """
    def __init__(self, bot: _BotController, light_port: int, reset_file_path: str) -> None: ...

class _StartPage(_tk.Frame):
    def __init__(self, parent: _tk.Frame, controller: IHSRunner) -> None: ...

class _ResetPage(_tk.Frame):
    def __init__(self, parent: _tk.Frame, controller: IHSRunner) -> None: ...

class _RunPage(_tk.Frame):
    def __init__(self, parent: _tk.Frame, controller: IHSRunner) -> None: ...
    def finish_calibration(self, thread: _threading.Thread): ...
    def update_sensor_value(self) -> None: ...
    def wait_for_light(self, thread: _threading.Thread): ...
    def set_light_off_value(self) -> None: ...
    def set_light_on_value(self) -> None: ...
